### ISSUE TITLE
Clear Navigation

### ISSUE THREAD

**Issue by katee145** [katee145/periodprofessionals#2]
**User story:**

As a visitor, I want clear navigation so that I can easily find sections relevant to me.

**Acceptance Criteria:**

- [x] A navigation bar with links to all necessary sections.
- [x] The navigation bar is stuck to the top of the page and collapses on smaller devices.
- [x] Each link accurately describes the destination section.

**Tasks:**

- [x] Add a navigation bar.
- [x] Style the navbar to be fixed at the top of the page and add collapsibility for mobile devices.
- [x] Ensure each link works and accurately describes the section.
