### ISSUE TITLE
External Resources

### ISSUE THREAD

**Issue by katee145** [katee145/periodprofessionals#3]
**User story:**

As someone who works in HR, I want a list of external resources so that I can further explore menstrual equity topics.

**Acceptance Criteria:**

- [x] At least four external resources are provided with descriptive labels.
- [x] Each resource link is easy to identify.
- [x] Links open in a new tab to avoid navigating away from the site.

**Tasks:**

- [x] Display external resources relevant to menstrual equity.
- [x] Style resource links as buttons.
- [x] Configure links to open in new tabs.
- [ ]
