### ISSUE TITLE
Employer Advice

### ISSUE THREAD

**Issue by katee145** [katee145/periodprofessionals#4]
**User story:**

As a business owner, I want to understand how periods can impact my employees so that I can make the workplace better for them.

**Acceptance Criteria:**

- [x] The website explains: "What is Menstrual Equity?" and "How It Affects the Workplace".
- [x] Each answer is easy to find and concise.
- [x] The information is accessible and easy to read on all screen sizes.

**Tasks:**

- [x] Create sections answering each question.
- [x] Ensure that each subsection’s content is clear and properly structured.
