### ISSUE TITLE
Employee Advice

### ISSUE THREAD

**Issue by katee145** [katee145/periodprofessionals#5]
**User story:**

As someone who menstruates, I want to know how to approach my work so that I can have my needs met at the office.

**Acceptance Criteria:**

- [x] The tips are presented as a list of at least four practical actions.
- [x] The tips are concise and easy to understand.
- [x] The section is easy to navigate to on the website.

**Tasks:**

- [x] Create and style the tips section.
- [x] Ensure tips are concise and clearly separated for readability.
