### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by katee145** [katee145/periodprofessionals#7]
**User story:**

As a potential supporter, I want to read testimonials so that I can see the impact of menstrual equity practices in the workplace.

**Acceptance Criteria:**

- [x] A testimonial section displays at least three testimonials with names and short comments.
- [x] Each testimonial is clearly formatted and easy to read.
- [x] The section is responsive on all devices.

**Tasks:**

- [x] Create a testimonial section with positive stories
- [x] Style for layout and spacing.
- [x] Test for readability and responsiveness on different devices.
